buildpack:
  name: Blazar-Buildpack-oss-fork

env:
  SKIP_VERSION_OVERRIDE_ON_BRANCH: hubspot
  MAVEN_BUILD_ARGS: -Drat.skip=true -Dspotless.check.skip=true


stepActivation:
  notify:
    branches: [hubspot]
